KQT.Web/Controllers/ArticleController.cs
using KQT.DataMigration;
using KQT.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KQT.Web.Controllers
{
    public class ArticleController : Controller
    {
        private readonly DataMigrationContext _context;

        public ArticleController()
        {
            _context = new DataMigrationContext();
        }

        // GET: News
        public ActionResult Index(string id)
        {
            var data = _context.NewsEntities.Find(id);
            if (data == null)
                return RedirectToAction("Index", "Home");
            var obj = new PageHeaderViewModel
            {
                IsHome = false,
                Author = "Trọng Khoa",
                CreatedDate = DateTime.UtcNow.ToString("dd/mm/yyy"),
                SubTitle = data.NewTitle,
                Title = data.NewTitleSale,
                Image = data.ImageHead,
                NewsDetail = data
            };
            //Tăng view người xem

            ++data.ViewCount;
            _context.SaveChanges();
            return View(obj);
        }

        public JsonResult GetNews(int? page)
        {
            var pageNumber = page ?? 1;
            var lst = _context.NewsEntities.OrderBy(x => x.CreatedDate)
                        .Select(x => new NewsViewModel
                        {
                            DateCreated = x.CreatedDate.Value,
                            Id = x.Id,
                            Title = x.NewTitle,
                            TitleDecs = x.NewTitleSale
                        })
                        .Skip((pageNumber - 1) * 4)
                        .Take(4).ToList();
            if (lst.Count > 0)
            {
                return Json(new JsonResponse { Success = true, Message = lst }, JsonRequestBehavior.AllowGet);
            }
            return Json(new JsonResponse { Success = false }, JsonRequestBehavior.AllowGet);
        }
    }
}

KQT.Web/Controllers/HomeController.cs
using KQT.Web.Models;
using System;
using System.Web.Mvc;

namespace KQT.Web.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            var obj = new PageHeaderViewModel
            {
                IsHome = true,
                Author = "Trọng Khoa",
                CreatedDate = DateTime.UtcNow.ToString("dd/mm/yyy"),
                SubTitle = "hihihehexinchao♥",
                Title = "Cháo các bạn",
                Image = "home-bg.jpg"
            };
            return View(obj);
        }

        public ActionResult About()
        {
            var obj = new PageHeaderViewModel
            {
                IsHome = true,
                SubTitle = "This is what I do.",
                Title = "About Me",
                Image = "about-bg.jpg"
            };
            return View(obj);
        }
    }
}

KQT.Web/Views/Home/About.cshtml
@model KQT.Web.Models.PageHeaderViewModel
@{
    ViewBag.Title = "About";
}
@section _PageHeader
{
    @Html.Partial("_PageHeaderPartial", Model)
}

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>

KQT.Web/Views/Home/Index.cshtml
@model KQT.Web.Models.PageHeaderViewModel

@{
    ViewBag.Title = "Blog";
}
@section _PageHeader
{
    @Html.Partial("_PageHeaderPartial", Model)
}
<!-- Main Content -->
<div id="mainContentNews">
</div>
<!-- Pager -->
<div class="clearfix">
    <a class="btn btn-primary float-right" href="javascript:void(0)" onclick="LoadMore()">Older Posts &rarr;</a>
</div>
@section scripts
{

    <script>
        $(function () {
            sessionStorage.setItem("pageNumber", 1);
            loadPage(1)
        })
        const LoadMore= () => {
            let page = sessionStorage.getItem("pageNumber");
            loadPage(++page)
            sessionStorage.setItem("pageNumber", page);
        }
        const loadPage = (page) => {
            $.ajax({
            url: '@Url.Action("GetNews","Article")'+ `?page=${page}`,
            type: 'GET',
            success: function (data) {
                if (data.Success=== true) {
                    const link = '@Url.Action("Index", "Article")';
                    data.Message.map(e => {
                        let linkdetail = `${link}?id=${e.Id}`;
                        $('#mainContentNews').append(`
                            <div class="post-preview">
                                <a href='${linkdetail}'>
                                    <h2 class="post-title">
                                        ${e.Title}
                                    </h2>
                                    <h3 class="post-subtitle">
                                        ${e.TitleDecs}
                                    </h3>
                                </a>
                                <p class="post-meta">
                                    Posted by
                                    <a href="https://www.facebook.com/KhoaPiterrr">Start KQT-hihihehe</a>
                                    on ${Date(e.DateCreated)}
                                </p>
                            </div>
                            <hr>

                        `)
                    })
                } else {
                    let page = sessionStorage.getItem("pageNumber");
                    sessionStorage.setItem("pageNumber", --page);
                }
            },
            error: function (result, textStatus, errorThrown) {
                debugger
                alert("Có lỗi", "Error:" + errorThrown + " - " + textStatus + " - " + result, "error");
            },
        });
        }
    </script>
}