KQT.Web/Areas/Admin/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KQT.Web.Areas.Admin.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Admin/Dashboard
        public ActionResult Index()
        {
            return View();
        }
    }
}

KQT.Web/Areas/Admin/Controllers/LoginController.cs
using HashPassword;
using KQT.DataMigration;
using KQT.Entity;
using KQT.Web.Areas.Admin.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KQT.Web.Areas.Admin.Controllers
{
    public class LoginController : Controller
    {
        private readonly DataMigrationContext _context;

        public LoginController()
        {
            _context = new DataMigrationContext();
        }

        // GET: Admin/Login
        public ActionResult Index()
        {
            if (Session[ConstantData.USER_SESSION] as NguoiDung != null)
            {
                return RedirectToAction("News", "News");
            }
            //string currenturl = AdminBaseController.strControlerCurrent;
            //ViewBag.Url = currenturl;
            HttpCookie cookie = Request.Cookies[ConstantData.USER_COOKIES];
            //Nhớ mật khẩu
            ViewBag.UserLogin = new LoginModel();
            ViewBag.UserLogin.username = string.Empty;
            ViewBag.UserLogin.password = string.Empty;
            if (cookie != null)
            {
                ViewBag.UserLogin.username = cookie[ConstantData.USERNAME_COOKIES].ToString();
                ViewBag.UserLogin.password = cookie[ConstantData.PASSWORD_COOKIES].ToString();
            }
            return View();
        }

        public ActionResult CheckLogin(string username, string pwd, string remember)
        {
            //Lưu trang hiện tại để khi đăng nhập thành công có thể đến
            //string currenturl = AdminBaseController.strControlerCurrent;
            //ViewBag.Url = currenturl;
            NguoiDung obj = getObjByUser(username);

            if (obj.Id > 0)
            {
                if (BCryptPassword.VerifyPassword(pwd, obj.MatKhau))
                { //Đăng nhập thành công
                    Session.Add(ConstantData.USER_SESSION, obj);
                    if (Convert.ToBoolean(remember))
                    {
                        HttpCookie cookie = new HttpCookie(ConstantData.USER_COOKIES);
                        cookie[ConstantData.USERNAME_COOKIES] = obj.TenDangNhap;
                        cookie[ConstantData.PASSWORD_COOKIES] = pwd;
                        cookie.Expires = DateTime.Now.AddDays(100);
                        Response.Cookies.Add(cookie);
                    }
                    return Json(new { error = false, message = "Đăng nhập thành công" });
                }
                return Json(new { error = true, message = "Mật khẩu không chính xác" });
            }
            return Json(new { error = true, message = "Tài khoản không chính xác" });
        }

        /// <summary>
        /// Hàm Lấy thông tin người dùng bằng username
        /// Author          Date            Comments
        /// KhoaLT        5/5/2019        Tạo mới
        /// </summary>
        /// <param name="user"></param>
        /// <returns></returns>
        public NguoiDung getObjByUser(string user)
        {
            try
            {
                return _context.NguoiDungs.Where(x => x.TenDangNhap.Equals(user)).First();
            }
            catch (Exception)
            {
                return new NguoiDung();
            }
        }

        public ActionResult Logout()
        {
            //AdminBaseController.strControlerCurrent = string.Empty;
            Session[ConstantData.USER_SESSION] = null;
            //Lưu nhật kí

            return RedirectToAction("Index", "login");
        }

        public JsonResult DoiMatKhau(string pwdhientai, string pwd1)
        {
            var objuser = (NguoiDung)Session[ConstantData.USER_SESSION];
            if (BCryptPassword.VerifyPassword(pwdhientai, objuser.MatKhau))
            {
                NguoiDung obj = _context.NguoiDungs.Find(objuser.Id);
                obj.MatKhau = BCryptPassword.GetHashPassword(pwd1);
                _context.SaveChanges();
                return Json(new JsonPostBack("Đổi mật khẩu thành công", true), JsonRequestBehavior.AllowGet);
            }
            return Json(new JsonPostBack("Mật khẩu hiện tại không chính xác", false), JsonRequestBehavior.AllowGet);
        }

        public ViewResult ChuaCoQuyen()
        {
            return View();
        }

        public ActionResult FogetPassword()
        {
            return View();
        }
    }
}

KQT.Web/Areas/Admin/Views/Login/FogetPassword.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Đăng nhập hệ thống</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
    <link href="~/Content/plugins/fontawesome-free/css/all.min.css" rel="stylesheet" />
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- icheck bootstrap -->
    <link href="~/Content/plugins/icheck-bootstrap/icheck-bootstrap.min.css" rel="stylesheet" />
    <!-- Theme style -->
    <link href="~/Content/dist/css/adminlte.min.css" rel="stylesheet" />
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition login-page">
    <div class="login-box">
        <div class="login-logo">
            <a href="../../index2.html"><b>Admin</b>KQT-blog</a>
        </div>
        <!-- /.login-logo -->
        <div class="card">
            <div class="card-body login-card-body">
                <p class="login-box-msg">Bạn đã quên mật khẩu ? Liện hệ hotline: 113 để chúng tôi có thể hỗ trợ bạn.</p>

                <form action="recover-password.html" method="post">

                    <div class="row">
                        <div class="col-12">
                            <a href="https://www.facebook.com/KhoaPiterrr" class="btn btn-primary btn-block">Liên hệ Facebook</a>
                        </div>
                        <!-- /.col -->
                    </div>
                </form>

                <p class="mt-3 mb-1">
                    <a href='@Url.Action("Index","Login")'>Login</a>
                </p>
            </div>
            <!-- /.login-card-body -->
        </div>
    </div>
    <!-- /.login-box -->
    <!-- jQuery -->
    <script src="~/Content/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/Content/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Content/dist/js/adminlte.min.js"></script>
</body>
</html>

KQT.Web/Areas/Admin/Views/Login/Index.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Đăng nhập hệ thống</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
    <link href="~/Content/plugins/fontawesome-free/css/all.min.css" rel="stylesheet" />
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- icheck bootstrap -->
    <link href="~/Content/plugins/icheck-bootstrap/icheck-bootstrap.min.css" rel="stylesheet" />
    <!-- Theme style -->
    <link href="~/Content/dist/css/adminlte.min.css" rel="stylesheet" />
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition login-page">
    <div class="login-box">
        <div class="login-logo">
            <a href="../../index2.html"><b>Admin</b>KQT-blog</a>
        </div>
        <!-- /.login-logo -->
        <div class="card">
            <div class="card-body login-card-body">
                <p class="login-box-msg">Đăng nhập hệ thống</p>

                <div class="input-group mb-3">
                    <input type="email" id="txtUserName" class="form-control" placeholder="Email">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-envelope"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="password" id="txtPwd" class="form-control" placeholder="Password">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-8">
                        <div class="icheck-primary">
                            <input type="checkbox" id="remember">
                            <label for="remember">
                                Remember Me
                            </label>
                        </div>
                    </div>
                    <!-- /.col -->
                    <div class="col-4">
                        <button onclick="DangNhap()" class="btn btn-primary btn-block">Sign In</button>
                    </div>
                    <!-- /.col -->
                </div>

                @*<div class="social-auth-links text-center mb-3">
                        <p>- OR -</p>
                        <a href="#" class="btn btn-block btn-primary">
                            <i class="fab fa-facebook mr-2"></i> Sign in using Facebook
                        </a>
                        <a href="#" class="btn btn-block btn-danger">
                            <i class="fab fa-google-plus mr-2"></i> Sign in using Google+
                        </a>
                    </div>*@
                <!-- /.social-auth-links -->

                <p class="mb-1">
                    <a href='@Url.Action("FogetPassword","Login")'>Quên mật khẩu</a>
                </p>
            </div>
            <!-- /.login-card-body -->
        </div>
    </div>
    <!-- /.login-box -->
    <!-- jQuery -->
    <script src="~/Content/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/Content/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Content/dist/js/adminlte.min.js"></script>
    <script>
        $('#txtPwd').keyup(function (e) {
            if (e.key == "Enter") {
                DangNhap()
            }
        })
        $('#txtUserName').keyup(function (e) {
            if (e.key == "Enter") {
                DangNhap()
            }
        })
        $(function () {
            $('#txtUserName').val('@ViewBag.UserLogin.username')
            $('#txtPwd').val('@ViewBag.UserLogin.password')
            if ('@ViewBag.UserLogin.username' !== '' && '@ViewBag.UserLogin.password' !== '') {
                $( "#remember" ).prop( "checked", true );
            }
        })
        function DangNhap() {
            //validation

            if ($('#txtUserName').val().trim() == '' || $('#txtPwd').val().trim() == '') {
                alert('Vui lòng kiểm tra lại thông tin đăng nhập','Thông báo')
                return;
            }
            let formData = new FormData();
            formData.append('username', $('#txtUserName').val());
            formData.append('pwd', $('#txtPwd').val());
            //Kiểm tra nhớ mật khẩu
            if ($('#rememberme').is(':checked')) {
                formData.append('remember', 'true')
            } else {
                formData.append('remember','false')
            }
            $.ajax({
                url: '@Url.Action("CheckLogin", "login")',
                data: formData,
                type: 'POST',
                success: function (data) {
                    if (data.error) {
                        alert('Lỗi '+data.message)
                    }
                    else {
                        //loadingStop();
                        window.location.href = '@Url.Action("Index", "Dashboard")'
                    }

                },
                error: function (error) {
                    alert(error)
                },
                cache: false,
                processData: false,
                contentType: false
            });

        }
    </script>
</body>
</html>