KQT.Web/Controllers/ContactCLientController.cs
using KQT.DataMigration;
using KQT.Entity;
using KQT.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KQT.Web.Controllers
{
    public class ContactCLientController : Controller
    {
        private readonly DataMigrationContext _context;

        public ContactCLientController()
        {
            _context = new DataMigrationContext();
        }

        // GET: Contact
        public ActionResult Index()
        {
            var obj = new PageHeaderViewModel
            {
                IsHome = true,
                Author = "Trọng Khoa",
                CreatedDate = DateTime.UtcNow.ToString("dd/mm/yyy"),
                SubTitle = "Have questions? I have answers.",
                Title = "Contact Me",
                Image = "contact-bg.jpg"
            };
            return View(obj);
        }

        [HttpPost]
        public JsonResult CreateContact(ContactEntity obj)
        {
            obj.Id = new DateTimeOffset(DateTime.Now).ToUnixTimeMilliseconds().ToString();
            _context.ContactEntities.Add(obj);
            _context.SaveChanges();
            return Json(new JsonResponse
            {
                Message = "Gửi phản hồi thành công",
                Success = true
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

KQT.Web/Views/ContactClient/Index.cshtml
@model KQT.Web.Models.PageHeaderViewModel
@{
    ViewBag.Title = "Liên hệ với chúng tôi";
}
@section _PageHeader
{
    @Html.Partial("_PageHeaderPartial", Model)
}

<p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon as possible!</p>
<form action="/ContactCLient/CreateContact" name="sentMessage" id="contactForm" novalidate>
    <div class="control-group">
        <div class="form-group floating-label-form-group controls">
            <label>Name</label>
            <input type="text" class="form-control" placeholder="Name" id="name" required data-validation-required-message="Please enter your name.">
            <p class="help-block text-danger"></p>
        </div>
    </div>
    <div class="control-group">
        <div class="form-group floating-label-form-group controls">
            <label>Email Address</label>
            <input type="email" class="form-control" placeholder="Email Address" id="email" required data-validation-required-message="Please enter your email address.">
            <p class="help-block text-danger"></p>
        </div>
    </div>
    <div class="control-group">
        <div class="form-group col-xs-12 floating-label-form-group controls">
            <label>Phone Number</label>
            <input type="tel" class="form-control" placeholder="Phone Number" id="phone" required data-validation-required-message="Please enter your phone number.">
            <p class="help-block text-danger"></p>
        </div>
    </div>
    <div class="control-group">
        <div class="form-group floating-label-form-group controls">
            <label>Message</label>
            <textarea rows="5" class="form-control" placeholder="Message" id="message" required data-validation-required-message="Please enter a message."></textarea>
            <p class="help-block text-danger"></p>
        </div>
    </div>
    <br>
    <div id="success"></div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary" id="sendMessageButton">Send</button>
    </div>
</form>
@section scripts {
    <script src="~/Content/js/jqBootstrapValidation.js"></script>
    <script src="~/Content/js/contact_me.js"></script>
    @*<script>
            const add = () => {
                let _data = {
                    Name: $('#name').val(),
                    Email: $('#email').val(),
                    Phone: $('#phone').val(),
                    Message: $('#message').val(),
                }

                $.ajax({
                    url: '@Url.Action("CreateContact","ContactCLient")',
                    data: JSON.stringify(_data),
                    type: 'POST',
                    success: function (data) {
                        if (data.Success) {

                        }
                        else {
                            alert('Looi xayre ra')
                        }
                    },
                    error: function (error) {
                        alert('loi cmnr'+error)
                    }

                });
            }
        </script>*@
}