KQT.Web/Models/NewsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KQT.Web.Models
{
    public class NewsViewModel
    {
        public string Id { get; set; }
        public string Title { get; set; }
        public string TitleDecs { get; set; }
        public DateTime DateCreated { get; set; }
    }
}

KQT.Web/Areas/Admin/Controllers/AdminHomeController.cs
using KQT.DataMigration;
using KQT.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KQT.Web.Areas.Admin.Controllers
{
    public class AdminHomeController : BaseAdminController
    {
        private DataMigrationContext db = new DataMigrationContext();

        // GET: Admin/AdminHome
        public ActionResult Index()
        {
            return View();
        }

        #region Người dùng

        public ActionResult NguoiDung()
        {
            List<NguoiDung> user = db.NguoiDungs.ToList();
            return View(user);
        }

        public ActionResult CreateNguoiDung()
        {
            ViewBag.ListVaiTro = new SelectList(db.VaiTros.ToList(), "Id", "TenVaiTro");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateNguoiDung(NguoiDung nguoiDung, HttpPostedFileBase fUpload)
        {
            if (ModelState.IsValid)
            {
                if (fUpload != null && fUpload.ContentLength > 0)
                {
                    fUpload.SaveAs(Server.MapPath("~/Content/img/User/" + fUpload.FileName));
                    nguoiDung.Avatar = fUpload.FileName;
                }
                else
                {
                    nguoiDung.Avatar = "default_user_image.png";
                }
                nguoiDung.NgayTao = DateTime.Now;
                db.NguoiDungs.Add(nguoiDung);
                db.SaveChanges();
                return RedirectToAction("NguoiDung");
            }
            return null;
        }

        [HttpGet]
        public ActionResult EditNguoiDung(int NguoiDungId)
        {
            NguoiDung user = db.NguoiDungs.SingleOrDefault(x => x.Id == NguoiDungId);
            ViewBag.ListVaiTro = new SelectList(db.VaiTros.ToList(), "Id", "TenVaiTro");
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditNguoiDung(NguoiDung nguoiDung, int id, HttpPostedFileBase fUpload)
        {
            NguoiDung nguoidungOld = db.NguoiDungs.Where(x => x.Id == id).First();
            if (ModelState.IsValid)
            {
                if (fUpload != null && fUpload.ContentLength > 0)
                {
                    fUpload.SaveAs(Server.MapPath("~/Content/img/User/" + fUpload.FileName));
                    nguoiDung.Avatar = fUpload.FileName;
                }
                db.Entry(nguoidungOld).CurrentValues.SetValues(nguoiDung);
                db.SaveChanges();
                return RedirectToAction("NguoiDung");
            }
            return null;
        }

        [HttpGet]
        public ActionResult DetailsNguoiDung(int NguoiDungId)
        {
            NguoiDung user = db.NguoiDungs.SingleOrDefault(x => x.Id == NguoiDungId);
            return View(user);
        }

        public ActionResult DeleteNguoiDung(int NguoiDungId)
        {
            NguoiDung user = db.NguoiDungs.SingleOrDefault(x => x.Id == NguoiDungId);
            if (user != null)
            {
                db.NguoiDungs.Remove(user);
                db.SaveChanges();
                return RedirectToAction("NguoiDung");
            }
            return View();
        }

        #endregion Người dùng

        private Boolean CheckFile(HttpPostedFileBase fUpload, string path)
        {
            if (fUpload != null && fUpload.ContentLength > 0)
            {
                fUpload.SaveAs(Server.MapPath("~/Content/img/" + path + "/ " + fUpload.FileName));
                return true;
            }
            return false;
        }
    }
}

KQT.Web/Areas/Admin/Controllers/NewsController.cs
using KQT.DataMigration;
using KQT.Entity;
using KQT.Web.Areas.Admin.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KQT.Web.Areas.Admin.Controllers
{
    public class NewsController : BaseAdminController
    {
        private DataMigrationContext db = new DataMigrationContext();

        #region News

        public ActionResult Index()
        {
            List<NewsEntity> news = db.NewsEntities.ToList();

            return View(news);
        }

        public ActionResult CreateNews()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateNews(NewsEntity news, HttpPostedFileBase fUploadHead, HttpPostedFileBase fUploadBody, HttpPostedFileBase fUploadFooter)
        {
            if (ModelState.IsValid)
            {
                if (CheckFile(fUploadHead, "News") != string.Empty)
                {
                    news.ImageHead = CheckFile(fUploadHead, "News");
                }
                if (CheckFile(fUploadBody, "News") != string.Empty)
                {
                    news.ImageBody = CheckFile(fUploadBody, "News");
                }
                if (CheckFile(fUploadFooter, "News") != string.Empty)
                {
                    news.ImageFooter = CheckFile(fUploadFooter, "News");
                }

                news.CreatedDate = DateTime.Now;
                news.Id = Guid.NewGuid().ToString();
                news.Status = 1;
                news.CreatedBy = (Session[ConstantData.USER_SESSION] as NguoiDung).Id.ToString();
                db.NewsEntities.Add(news);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return null;
        }

        [HttpGet]
        public ActionResult EditNews(string id)
        {
            NewsEntity news = db.NewsEntities.FirstOrDefault(x => x.Id == id);
            return View(news);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult EditNews(NewsEntity news, string id, HttpPostedFileBase fUploadHead, HttpPostedFileBase fUploadBody, HttpPostedFileBase fUploadFooter)
        {
            if (ModelState.IsValid)
            {
                if (CheckFile(fUploadHead, "News") != string.Empty)
                {
                    news.ImageHead = CheckFile(fUploadHead, "News");
                }
                if (CheckFile(fUploadBody, "News") != string.Empty)
                {
                    news.ImageBody = CheckFile(fUploadBody, "News");
                }
                if (CheckFile(fUploadFooter, "News") != string.Empty)
                {
                    news.ImageFooter = CheckFile(fUploadFooter, "News");
                }

                news.UpdatedDate = DateTime.Now;
                NewsEntity oldNews = db.NewsEntities.FirstOrDefault(x => x.Id == id);
                news.CreatedDate = (oldNews.CreatedDate == null) ? DateTime.Now : oldNews.CreatedDate;
                db.Entry(oldNews).CurrentValues.SetValues(news);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return null;
        }

        [HttpGet]
        public ActionResult DetailsNews(string id)
        {
            NewsEntity news = db.NewsEntities.FirstOrDefault(x => x.Id == id);
            return View(news);
        }

        public JsonResult DeleteNews(string id)
        {
            try
            {
                var data = db.NewsEntities.FirstOrDefault(x => x.Id == id);
                if (data == null)
                {
                    return Json(new
                    {
                        Success = false,
                        Message = "Không tìm thấy đối tượng cần xóa."
                    }, JsonRequestBehavior.AllowGet);
                }
                db.NewsEntities.Remove(data);
                db.SaveChanges();
                return Json(new
                {
                    Success = true,
                    Message = "Xóa thành công kích thước này."
                }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new
                {
                    Success = false,
                    Message = "Không thể xóa đối tượng này. Vì sẽ ảnh hưởng đến dữ liệu khác." + ex.Message
                }, JsonRequestBehavior.AllowGet);
            }
        }

        #endregion News

        private string CheckFile(HttpPostedFileBase fUpload, string path)
        {
            if (fUpload != null && fUpload.ContentLength > 0)
            {
                var id = new DateTimeOffset(DateTime.Now).ToUnixTimeMilliseconds().ToString();
                var fileName = $"~/Content/img/News/{id}{fUpload.FileName}";
                fUpload.SaveAs(Server.MapPath(fileName));
                return $"{id}{fUpload.FileName}";
            }
            return string.Empty;
        }
    }
}

KQT.Web/Areas/Admin/Views/News/CreateNews.cshtml
@model KQT.Entity.NewsEntity

@{
    ViewBag.Title = "CreateNews";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Quản lý tin tức</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item">Tin tức </li>
                    <li class="breadcrumb-item active">Thêm mới </li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<section>
    <div class="row">
        <div class="col-12">
            <div class="card">
                @using (Html.BeginForm("CreateNews", "News", FormMethod.Post, new { encType = "multipart/form-data" }))
                {
                    <div class="card-header">
                        <div class="row">
                            <div class="col-md-6">
                                <h3 class="card-title">Thêm mới tin tức</h3>
                            </div>
                            <div class="col-md-6 text-right">
                                <a href='@Url.Action("Index", "News")' class="btn btn-danger"> Danh sách</a>
                                &nbsp;
                                @*<input id="btnThem" type="button" value="Thêm" class="btn btn-warning" />*@
                                <button type="submit" id="btnThem" class="btn btn-warning"><i class="fas fa-save"></i> Lưu</button>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            <h3>Thêm mới tin tức</h3>
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            <div class="form-group">
                                <lable class="control-label col-md-2">Tiêu đề</lable>
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.NewTitle, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.NewTitle, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <lable class="control-label col-md-2">Tiêu đề phụ</lable>
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.NewTitleSale, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.NewTitleSale, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <lable class="control-label col-md-2">Thông tin phần đầu</lable>
                                <div class="col-md-10">
                                    @Html.TextAreaFor(model => model.NewContentHead, new { @class = "ckeditor" })
                                    @Html.ValidationMessageFor(model => model.NewContentHead, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <lable class="control-label col-md-2">Thông tin phần thân</lable>
                                <div class="col-md-10">
                                    @Html.TextAreaFor(model => model.NewContentBody, new { @class = "ckeditor" })
                                    @Html.ValidationMessageFor(model => model.NewContentBody, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <lable class="control-label col-md-2">Thông tin phần cuối</lable>
                                <div class="col-md-10">
                                    @Html.TextAreaFor(model => model.NewContentFooter, new { @class = "ckeditor" })
                                    @Html.ValidationMessageFor(model => model.NewContentFooter, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <lable class="control-label col-md-2">Ảnh phần đầu</lable>
                                <div class="col-md-10">
                                    <img id="imgHead" alt="Image Head" style="height:200px;width:250px" />
                                    <input type='file' id="fUploadHead" name="fUploadHead" />
                                    @Html.ValidationMessageFor(model => model.ImageHead, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <lable class="control-label col-md-2">Ảnh phần thân</lable>
                                <div class="col-md-10">
                                    <img id="imgBody" alt="Image Body" style="height:200px;width:250px" />
                                    <input type='file' id="fUploadBody" name="fUploadBody" />
                                    @Html.ValidationMessageFor(model => model.ImageBody, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <lable class="control-label col-md-2">Ảnh phần cuối</lable>
                                <div class="col-md-10">
                                    <img id="imgFooter" alt="Image footer" style="height:200px;width:250px" />
                                    <input type='file' id="fUploadFooter" name="fUploadFooter" />
                                    @Html.ValidationMessageFor(model => model.ImageFooter, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <lable class="control-label col-md-2">Từ khóa tìm kiếm</lable>
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.MetaKeyword, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.MetaKeyword, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <lable class="control-label col-md-2">Mô tả</lable>
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.MetaDescription, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.MetaDescription, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div style="margin-left:20px;">
                            @Html.ActionLink("Trở lại", "Index")
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</section>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        function readURL(input, type) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#img' + type).attr('src', e.target.result);
                };

                reader.readAsDataURL(input.files[0]); // convert to base64 string
            }
        };

        $("#fUploadHead").change(function () {
            readURL(this, "Head");
        });
        $("#fUploadBody").change(function () {
            readURL(this, "Body");
        });
        $("#fUploadFooter").change(function () {
            readURL(this, "Footer");
        });
    </script>
}

KQT.Web/Areas/Admin/Views/News/Index.cshtml
@model IEnumerable<KQT.Entity.NewsEntity>

@{
    ViewBag.Title = "Bài viết";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Quản lý tin tức</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Tin tức </li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<section class="content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-6">
                            <h3 class="card-title">Vai trò</h3>
                        </div>
                        <div class="col-md-6 text-right">
                            <a class="btn btn-primary" href="@Url.Action("CreateNews", "News")"> Thêm mới</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <table id="dtTable" class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>
                                    Mã tin tức
                                </th>
                                <th>
                                    Tiêu đề
                                </th>
                                <th>
                                    Tiêu đề phụ
                                </th>
                                <th>
                                    Lượt xem
                                </th>
                                <th>
                                    Trạng thái
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Id)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.NewTitle)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.NewTitleSale)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.ViewCount)
                                    </td>

                                    <td>
                                        @Html.ActionLink("Sửa", "EditNews", new { id = item.Id }, new { @class = "btn btn-default", @style = "background-color:#dfdaeb" }) |
                                        @Html.ActionLink("Chi tiết", "DetailsNews", new { id = item.Id }, new { @class = "btn btn-info" }) |
                                        <a href="javascript:void(0)" onclick="xoatintuc('@item.Id')" class="btn btn-danger">Xóa</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>
@section scripts{
    <script src="~/Content/plugins/jquery/jquery.js"></script>
    <script src="~/Content/plugins/datatables/jquery.dataTables.js"></script>
    <script src="~/Content/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
    <script>
        $(function () {
            $('#dtTable').DataTable();
        });

        const xoatintuc = (id) => {
            Swal.fire({
                title: 'Bạn chắc chắn sẽ xóa?',
                text: "Bạn sẽ không thể khôi phục bản ghi này!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Xóa'
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        url: '@Url.Action("DeleteNews", "AdminHome")' + `?id=${id}`,
                        type: 'POST',
                        success: function (data) {
                            if (data.Success) {
                               Swal.fire(
                                    'Deleted!',
                                    'Xóa tin tức thành công',
                                    'success'
                                )
                                location.reload();
                            }
                            else {
                              Swal.fire(
                                    'Deleted!',
                                    'Xóa tin tức thành công',
                                    'danger'
                                )
                            }
                        },
                         error: function (error) {
                             alert('Lỗi ajax' + error)
                        },
                        cache: false,
                        processData: false,
                        contentType: false
                    });
                }
            })
        }
    </script>
}

KQT.Web/Areas/Admin/Views/News/News.cshtml
@model IEnumerable<KQT.Entity.NewsEntity>

@{
    ViewBag.Title = "Bài viết";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Quản lý tin tức</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Tin tức </li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<section class="content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-6">
                            <h3 class="card-title">Vai trò</h3>
                        </div>
                        <div class="col-md-6 text-right">
                            <a class="btn btn-primary" href="@Url.Action("CreateNews", "News")"> Thêm mới</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <table id="dtTable" class="table table-bordered table-hover">
                        <thead>
                            <tr>
                                <th>
                                    Mã tin tức
                                </th>
                                <th>
                                    Tiêu đề
                                </th>
                                <th>
                                    Tiêu đề phụ
                                </th>
                                <th>
                                    Người viết
                                </th>
                                <th>
                                    Ngày tạo
                                </th>
                                <th>
                                    Người sửa
                                </th>
                                <th>
                                    Ngày sửa
                                </th>
                                <th>
                                    Lượt xem
                                </th>
                                <th>
                                    Trạng thái
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Id)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.NewTitle)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.NewTitleSale)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CreatedBy)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CreatedDate)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.UpdatedBy)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.UpdatedDate)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.ViewCount)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Status)
                                    </td>

                                    <td>
                                        @Html.ActionLink("Sửa", "EditNews", new { id = item.Id }, new { @class = "btn btn-default", @style = "background-color:#dfdaeb" }) |
                                        @Html.ActionLink("Chi tiết", "DetailsNews", new { id = item.Id }, new { @class = "btn btn-info" }) |
                                        <a href="javascript:void(0)" onclick="xoatintuc('@item.Id')" class="btn btn-danger">Xóa</a>
                                    </td>
                                </tr>
                             }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>
@section scripts{
    <script src="~/Content/plugins/jquery/jquery.js"></script>
    <script src="~/Content/plugins/datatables/jquery.dataTables.js"></script>
    <script src="~/Content/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
    <script>
        $(function () {
            $('#dtTable').DataTable();
        });

        const xoatintuc = (id) => {
            Swal.fire({
                title: 'Bạn chắc chắn sẽ xóa?',
                text: "Bạn sẽ không thể khôi phục bản ghi này!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Xóa'
            }).then((result) => {
                if (result.value) {
                    $.ajax({
                        url: '@Url.Action("DeleteNews", "AdminHome")' + `?id=${id}`,
                        type: 'POST',
                        success: function (data) {
                            if (data.Success) {
                               Swal.fire(
                                    'Deleted!',
                                    'Xóa tin tức thành công',
                                    'success'
                                )
                                location.reload();
                            }
                            else {
                              Swal.fire(
                                    'Deleted!',
                                    'Xóa tin tức thành công',
                                    'danger'
                                )
                            }
                        },
                         error: function (error) {
                             alert('Lỗi ajax' + error)
                        },
                        cache: false,
                        processData: false,
                        contentType: false
                    });
                }
            })
        }
    </script>
}